#
# Makefile for bit2spr.c
# Created by Marc David Rovner (mrovner@ic.sunysb.edu)
# June 7th, 1992
#

CC = cc
CFLAGS = -g

bit2spr: bit2spr.c
	${CC} ${CFLAGS} bit2spr.c -o bit2spr

clean:
	rm -rf bit2spr
